version: 1.0.{build}
nuget:
  project_feed: true
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - set
  - bundle install
build_script:
  - rake publish
artifacts:
- path: src\**\*.nupkg
environment:
  NUGET_KEY:
    secure: 5m1zupizmNvVwCg2MDUkRGQbbVfNypLo9yCstTAXQ5KHDypBe5RrGKi1HnEAhAy8